export const contactForm = {
  id: 'contact-form',
  submitButton: {
    text: 'SHIP IT',
  },
  fields: [
    {
      name: 'full_name',
      label: 'Full name',
      placeholder: 'TYPE HERE',
      required: true,
      type: 'text',
      inputType: 'single_line_text',
    },
    {
      name: 'company',
      label: 'Company',
      placeholder: 'TYPE HERE',
      required: false,
      type: 'text',
      inputType: 'single_line_text',
    },
    {
      name: 'email',
      label: 'Email',
      placeholder: 'TYPE HERE',
      required: true,
      type: 'email',
      inputType: 'single_line_text',
    },
    {
      name: 'what_are_you_looking_to_improve',
      label: 'What are you looking to improve?',
      placeholder: 'SELECT',
      required: true,
      inputType: 'dropdown',
      options: [
        'AI Strategy / Operating Model',
        'Research & Knowledge Workflows',
        'Agentic Workflows',
        'Custom AI Software',
        'Not sure yet',
      ],
    },
    {
      name: 'timeline_expectation',
      label: 'Timeline',
      placeholder: 'SELECT',
      required: false,
      inputType: 'dropdown',
      options: [
        'As soon as possible',
        'Within 1–3 months',
        'Within 3–6 months',
        'Exploring for later',
      ],
    },
    {
      name: 'how_you_found_us',
      label: 'How did you find me?',
      placeholder: 'TYPE HERE',
      required: false,
      type: 'text',
      inputType: 'single_line_text',
    },
    {
      name: 'favorite_movie_or_album',
      label: 'Favourite movie or album',
      placeholder: 'TYPE HERE',
      required: false,
      type: 'text',
      inputType: 'single_line_text',
    },
    {
      name: 'description',
      label: 'Tell me about your current setup or challenge',
      placeholder:
        'How does your team work today, where do you see friction, and what would you like to improve?',
      required: true,
      inputType: 'multi_line_text',
    },
  ],
}
