export const contactForm = {
  id: 'contact-form',
  submitButton: {
    text: 'SHIP IT',
  },
  fields: [
    {
      name: 'full_name',
      label: 'Full name',
      placeholder: 'TYPE HERE',
      required: true,
      type: 'text',
      inputType: 'single_line_text',
    },
    {
      name: 'company',
      label: 'Company',
      placeholder: 'TYPE HERE',
      required: false,
      type: 'text',
      inputType: 'single_line_text',
    },
    {
      name: 'email',
      label: 'Email',
      placeholder: 'TYPE HERE',
      required: true,
      type: 'email',
      inputType: 'single_line_text',
    },
    {
      name: 'project_scope',
      label: 'Project scope',
      placeholder: 'SELECT',
      required: true,
      inputType: 'dropdown',
      options: [
        'Brand identity',
        'Website design',
        'Development',
        'Strategy',
        'Something else',
      ],
    },
    {
      name: 'budget_expectation',
      label: 'Budget expectation',
      placeholder: 'SELECT',
      required: false,
      inputType: 'dropdown',
      options: ['Under 10k', '10k – 25k', '25k – 50k', '50k+', 'Not sure yet'],
    },
    {
      name: 'timeline_expectation',
      label: 'Timeline expectation',
      placeholder: 'SELECT',
      required: false,
      inputType: 'dropdown',
      options: ['ASAP', 'Within 1 month', 'Within 3 months', 'Flexible'],
    },
    {
      name: 'how_you_found_us',
      label: 'How did you find us?',
      placeholder: 'TYPE HERE',
      required: false,
      type: 'text',
      inputType: 'single_line_text',
    },
    {
      name: 'favorite_movie_or_album',
      label: 'Favourite movie or album',
      placeholder: 'TYPE HERE',
      required: false,
      type: 'text',
      inputType: 'single_line_text',
    },
    {
      name: 'description',
      label: 'Tell us about your project',
      placeholder: 'TYPE HERE',
      required: true,
      inputType: 'multi_line_text',
    },
  ],
}
