#import "../fragments/link.graphql"
#import "../fragments/image.graphql"

query studioTitanEntryQuery($preview: Boolean!) {
  studioTitan(id: "5O5FgOdUFQPAY3GuGTQG53", preview: $preview) {
    sys {
      id
    }
    principles
    about {
      json
    }
    phoneNumber
    email
  }
}

query footerEntryQuery($preview: Boolean!) {
  footer(id: "5I7agtZ6v3LyVo3mlmPDcj", preview: $preview) {
    sys {
      id
    }
    linksCollection {
      items {
        ...Link
      }
    }
  }
}

query contactEntryQuery($preview: Boolean!) {
  contact(id: "vY0YUX2NNRKObRnLhLELc", preview: $preview) {
    sys {
      id
    }
    description {
      json
    }
    form
    faqsCollection {
      items {
        title
        content {
          json
        }
      }
    }
    thankYouMessage {
      json
    }
  }
}

query projectListEntryQuery($preview: Boolean!) {
  projectList(id: "519KOpAG8hCJRyr2RdO3Jm", preview: $preview) {
    sys {
      id
    }
    listCollection {
      items {
        sys {
          id
        }
        name
        industry
        body {
          json
        }
        testimonial
        assetsCollection(limit: 20) {
          items {
            url
            title
            contentType
            width
            height
          }
        }
        services
        stack
        link
      }
    }
  }
}


# query projectCollectionQuery($preview: Boolean!) {
#   projectCollection(preview: $preview) {
#     items {
#       sys {
#         id
#       }
#       name
#       industry
#       description
#       testimonial
#       assetsCollection(limit: 20) {
#         items {
#           imagesCollection(limit: 20) {
#             items {
#               url
#               title
#             }
#           }
#         }
#       }
#       services
#       stack
#       link
#       publishedDate
#     }
#   }
# }
